source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/denizztret/BountyKit.git'

platform :ios, "6.0"

pod 'BountyKit', :git => 'https://github.com/denizztret/BountyKit.git'
pod 'cocos2d', :podspec => 'cocos2d.podspec'